task:
  container:
    image: openjdk:7-jdk
    cpu: 8
    memory: 12G
  timeout_in: 190m
  c_cache:
    folder: ~/.ccache
    populate_script: apt-get update && apt-get -qq install -y ccache
#services:
#  - docker
#before_install:
#- docker pull lineageos4microg/docker-lineage-cicd
#- git clone git://github.com/RR-msm7x30/android_device_samsung_ancora.git -b cm-12.1 device/samsung/ancora
#- docker run -e "BRANCH_NAME=cm-12.1" -e "DEVICE_LIST=ancora" -v "/home/user/lineage:/srv/src" -v "/home/user/zips:/srv/zips" -v "/home/user/logs:/srv/logs" -v "/home/user/cache:/srv/ccache" -e "INCLUDE_PROPRIETARY=false" -v "$(pwd):/srv/local_manifests"  lineageos4microg/docker-lineage-cicd
  build_script:
# Install dependency
    - apt-get update
    - apt-get -qq install software-properties-common
    - apt-get  -qq install -y dpkg bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev subversion git > /dev/null
    - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ bionic main"
    - sudo apt-get  -qq update 
    - sudo apt  -qq install -y libfl2 > /dev/null
#    - add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ bionic main"
#- wget http://ftp.br.debian.org/debian/pool/main/f/flex/libfl2_2.6.4-6.1_amd64.deb
#- sudo dpkg -i libfl2_2.6.4-6.1_amd64.deb
#- sudo add-apt-repository ppa:ubuntu-toolchain-r/test
#    - apt-get  -qq update 
#    - apt  -qq install libfl2
# getting UberTC
#    - git clone  --depth=1 "https://bitbucket.org/matthewdalex/arm-eabi-7.x" "../arm-eabi-7.x"
#    - export CROSS_COMPILE="$(pwd)/../arm-eabi-7.x/bin/arm-eabi-"
    - ldconfig
    - export USE_CCACHE=1
#    - export CCACHE_COMPRESS=""
    - ccache -M 1.2G
#Fix mesg n stdin: is not a tty
    - sed -i '/mesg[[:space:]]n/d' ~/.profile
    - cat .profile >> ~/.profile
    - chmod +x build-chromium.sh
    - timeout 115m ./build-chromium.sh && echo "Timeout"
    - ls -l
  environment:
   AUTH_TOKEN: ENCRYPTED[7fd3fbd1f11a828ebde512294486d28def548987c0b3c5934b3bbb7a87e2cf50fa84ae084b0ea99f04961c0633488156]
  publish_script:
   - chmod +x upload-release.sh
   - cp upload-release.sh ~/android/lineage/out/target/product/ancora/
   - cd ~/android/lineage/out/target/product/ancora/
  # - for file in *.zip; do ./upload-release.sh github_api_token=$AUTH_TOKEN owner=mtlive repo=cm12.1-build-ancora tag=$(date +%Y-%m-%d) filename=./$file ; done;

